#!/usr/bin/env bash
# Bash script that runs indefinitely
handle_sigterm() {
	echo "I am invincible!!!"
	exit 0
}

trap 'handle_sigterm' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
