#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
IFS=":"
while read -r username x userid x homedir x; do
	echo "Username: $username"
	echo "User ID: $userid"
	echo "Home Directory: $homedir"
done < "/etc/passwd"
