#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and one hi
i=0
while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	fi

	if [ $i -ne 9 ]; then
		echo "Best School"
	fi

	((i++))
done
