#!/usr/bin/env bash
# script that configures an Ubuntu server with some requirements.

if [ -f "/.dockerenv" ]; then
	echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
	echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
else
	exit 1
fi
