#!/usr/bin/env bash
# script that configures an Ubuntu server with some requirements.

if [ -f "/.dockerenv" ]; then
	cp /etc/hosts /etc/hosts.backup

	echo "127.0.0.2		localhost" > /etc/hosts.new
	echo "8.8.8.8		facebook.com" >> /etc/hosts.new

	cp -f /etc/hosts.new /etc/hosts

else
	exit 1
fi
