#!/usr/bin/env bash
# displays all active IPv4 IPs on the machine it’s executed on.

ipv4=$(ip -o -4 addr show scope global | awk '{print $4}' | cut -d'/' -f1)

for ip_address in $ipv4; do
	echo "$ip_address"
done
